# Generated by Django 3.1 on 2020-08-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_model_manager", "0004_auto_20200807_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company_model_manager.node",
            ),
        ),
    ]
